name: chirpsdk_example
description: Demonstrates how to use the chirpsdk plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  simple_permissions: ^0.1.9
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  chirpsdk:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: MarkPro
      fonts:
        - asset: fonts/MarkPro-Medium.ttf
        - asset: fonts/MarkPro-Bold.ttf
    - family: Calibre
      fonts:
        - asset: fonts/Calibre-Medium.ttf
        - asset: fonts/CalibreLight.ttf
        - asset: fonts/CalibreRegular.ttf
